//ROS typedefs
#include "ros/ros.h"
#include <geometry_msgs/PoseStamped.h>
#include <sensor_msgs/PointCloud2.h>

/* protected region user include files on begin */
/* protected region user include files end */

class PCAPoseEstimation_config
{
public:

};

class PCAPoseEstimation_data
{
// autogenerated: don't touch this class
public:
//input data
    	sensor_msgs::PointCloud2 in_inputPointCloud;
  
	
//output data
    	geometry_msgs::PoseStamped out_estimatedPose;
 

};

class PCAPoseEstimation_impl
{
	/* protected region user member variables on begin */
	/* protected region user member variables end */

public:
    PCAPoseEstimation_impl() 
    {
        /* protected region user constructor on begin */
		/* protected region user constructor end */
    }
    void configure(PCAPoseEstimation_config config) 
    {
        /* protected region user configure on begin */
		/* protected region user configure end */
    }
    void update(PCAPoseEstimation_data &data, PCAPoseEstimation_config config)
    {
        /* protected region user update on begin */
		/* protected region user update end */
    }

    
    /* protected region user additional functions on begin */
	/* protected region user additional functions end */
    
};
