//ROS typedefs
#include "ros/ros.h"
#include <pcl/PolygonMesh.h>
#include <sensor_msgs/PointCloud2.h>

/* protected region user include files on begin */
/* protected region user include files end */

class MeshGenerator_config
{
public:

};

class MeshGenerator_data
{
// autogenerated: don't touch this class
public:
//input data
    	sensor_msgs::PointCloud2 in_pointCloud;
  
	
//output data
    	pcl::PolygonMesh out_mesh;
 

};

class MeshGenerator_impl
{
	/* protected region user member variables on begin */
	/* protected region user member variables end */

public:
    MeshGenerator_impl() 
    {
        /* protected region user constructor on begin */
		/* protected region user constructor end */
    }
    void configure(MeshGenerator_config config) 
    {
        /* protected region user configure on begin */
		/* protected region user configure end */
    }
    void update(MeshGenerator_data &data, MeshGenerator_config config)
    {
        /* protected region user update on begin */
		/* protected region user update end */
    }

    
    /* protected region user additional functions on begin */
	/* protected region user additional functions end */
    
};
