//ROS typedefs
#include "ros/ros.h"
#include <sensor_msgs/PointCloud2.h>
#include <sensor_msgs/PointCloud2.h>

/* protected region user include files on begin */
/* PCL includes */
#include <pcl/point_types.h>
#include <pcl/io/pcd_io.h>

/* BRICS_3D includes */
#include <algorithm/filtering/Octree.h>
#include <util/PCLTypecaster.h>

/* protected region user include files end */

class Filter_config
{
public:
		std::string packedParameterSet;

};

class Filter_data
{
// autogenerated: don't touch this class
public:
//input data
    	sensor_msgs::PointCloud2 in_inputPointCloud;
  
	
//output data
    	sensor_msgs::PointCloud2 out_outputPointCloud;
 

};

class Filter_impl
{
	/* protected region user member variables on begin */
	BRICS_3D::IFiltering* filter;
	/* protected region user member variables end */

public:
    Filter_impl() 
    {
        /* protected region user constructor on begin */
		/* protected region user constructor end */
    }
    void configure(Filter_config config) 
    {
        /* protected region user configure on begin */
    	filter = new BRICS_3D::Octree();
		/* protected region user configure end */
    }
    void update(Filter_data &data, Filter_config config)
    {
        /* protected region user update on begin */
    	//Declaration and instantiation of a cloud pointer to be used for output
    	pcl::PointCloud<pcl::PointXYZ>::Ptr inputPointCloutPcl(new pcl::PointCloud<pcl::PointXYZ>);
    	pcl::PointCloud<pcl::PointXYZ>::Ptr outputPointCloutPcl(new pcl::PointCloud<pcl::PointXYZ>);
    	pcl::fromROSMsg(data.in_inputPointCloud, *inputPointCloutPcl);

    	BRICS_3D::PointCloud3D inputPointCloud;
    	BRICS_3D::PointCloud3D outputPointCloud;

    	BRICS_3D::PCLTypecaster caster;
    	caster.convertToBRICS3DDataType(inputPointCloutPcl, &inputPointCloud);

    	ROS_INFO("Filtering.");
    	filter->filter(&inputPointCloud, &outputPointCloud);

    	caster.convertToPCLDataType(outputPointCloutPcl, &outputPointCloud);
    	pcl::toROSMsg(*outputPointCloutPcl, data.out_outputPointCloud);

    	/* protected region user update end */
    }

    
    /* protected region user additional functions on begin */
	/* protected region user additional functions end */
    
};
