//ROS typedefs
#include "ros/ros.h"
#include <sensor_msgs/PointCloud2.h>
#include <brics_3d_msgs/PointCloudSegments.h>

/* protected region user include files on begin */
/* protected region user include files end */

class ForEachSegment_config
{
public:

};

class ForEachSegment_data
{
// autogenerated: don't touch this class
public:
//input data
    	brics_3d_msgs::PointCloudSegments in_allSegments;
  
	
//output data
    	sensor_msgs::PointCloud2 out_segment;
 

};

class ForEachSegment_impl
{
	/* protected region user member variables on begin */
	/* protected region user member variables end */

public:
    ForEachSegment_impl() 
    {
        /* protected region user constructor on begin */
		/* protected region user constructor end */
    }
    void configure(ForEachSegment_config config) 
    {
        /* protected region user configure on begin */
		/* protected region user configure end */
    }
    void update(ForEachSegment_data &data, ForEachSegment_config config)
    {
        /* protected region user update on begin */
/* In case of regenerate model: please replace this part */
//        void update()
//        {
//            component_implementation_.update(component_data_, component_config_);
//				segment_.publish(component_data_.out_segment);
//
//        }

    	/* by  this part */
//        void update()
//        {
//            component_implementation_.update(component_data_, component_config_);
//            for (unsigned int i = 0; i < component_data_.in_allSegments.segments.size(); ++i) {
//				segment_.publish(component_data_.in_allSegments.segments[i]);
//			}
//        }

		/* protected region user update end */
    }

    
    /* protected region user additional functions on begin */
	/* protected region user additional functions end */
    
};
